begin;
set search_path=public,extensions;
select no_plan();
select set_config('request.jwt.claim.sub',md5('user-1-agent')::uuid::text,true);
select ok(not private.platform('quality.read'),'ordinary professional has no quality capability');
insert into platform_admins(id,capabilities) values(md5('user-1-agent')::uuid,array['quality.read']);
select ok(private.platform('quality.read'),'explicit active platform capability is supported');
select ok(not private.platform('catalog.manage'),'quality does not imply other platform rights');
select ok(exists(select 1 from audit_events where entity_id=md5('user-1-agent')::uuid and changes::text like '%quality.read%'),'capability assignment is transactionally audited');
set local role authenticated;
select is((select count(*) from platform_admins),1::bigint,'RLS exposes only own active platform row');
select throws_ok($$update platform_admins set capabilities=array['catalog.manage']$$,'42501',null,'browser cannot write platform capabilities');
reset role;
update platform_admins set active=false where id=md5('user-1-agent')::uuid;
select ok(not private.platform('quality.read'),'inactive platform identity denied');
set local role authenticated;
select is((select count(*) from platform_admins),0::bigint,'inactive platform row hidden by RLS');
reset role;
select throws_ok($$update platform_admins set capabilities=array['quality.write']$$,'23514',null,'unknown write capability rejected');
select * from finish();
rollback;
