begin;
create extension if not exists pgtap with schema extensions;
set search_path=public,extensions;
select no_plan();
select ok(not has_function_privilege('authenticated','public.mark_invitation_sent(uuid,uuid)','execute'),'Auth bridge is not callable by authenticated users');
select ok(not has_function_privilege('anon','public.mark_invitation_sent(uuid,uuid)','execute'),'Auth bridge is not callable anonymously');
select ok(has_function_privilege('service_role','public.mark_invitation_sent(uuid,uuid)','execute'),'Auth bridge explicitly available to service role');
select ok(not has_function_privilege('authenticated','private.require_admin(uuid)','execute'),'internal privileged helpers are not directly callable');
select is((select count(*) from organizations),3::bigint,'three fictitious organizations');
select ok(exists(select 1 from pg_extension where extname='postgis'),'PostGIS real extension');
select ok(exists(select 1 from pg_indexes where indexname='territories_geometry_gist'),'GiST index');
select is((select count(*) from pg_tables where schemaname='public' and tablename not in ('spatial_ref_sys') and not rowsecurity),0::bigint,'all business tables have RLS');
select throws_ok($$insert into sla_policies(organization_id) values(md5('org-1')::uuid)$$,'23505',null,'nullable organization SLA scope really unique');
select throws_ok($$insert into service_schedules(organization_id) values(md5('org-1')::uuid)$$,'23505',null,'nullable organization schedule unique');
insert into sla_policies(organization_id,service_id) values(md5('org-1')::uuid,md5('service-1')::uuid);
select throws_ok($$insert into sla_policies(organization_id,service_id) values(md5('org-1')::uuid,md5('service-1')::uuid)$$,'23505',null,'service-only SLA unique');
insert into sla_policies(organization_id,category_id) select md5('org-1')::uuid,id from categories limit 1;
select throws_ok($$insert into sla_policies(organization_id,category_id) select md5('org-1')::uuid,id from categories limit 1$$,'23505',null,'category-only SLA unique');
insert into sla_policies(organization_id,service_id,category_id) select md5('org-1')::uuid,md5('service-1')::uuid,id from categories limit 1;
select throws_ok($$insert into sla_policies(organization_id,service_id,category_id) select md5('org-1')::uuid,md5('service-1')::uuid,id from categories limit 1$$,'23505',null,'combined SLA unique');
select throws_ok($$insert into service_memberships(organization_id,membership_id,service_id) values(md5('org-1')::uuid,md5('member-1-agent')::uuid,md5('service-2')::uuid)$$,'23503',null,'cross-tenant service FK');
select throws_ok($$insert into organization_memberships(organization_id,user_id,role) values(md5('org-2')::uuid,md5('user-1-agent')::uuid,'agent')$$,'23505',null,'one organization per user');
select throws_ok($$update organization_memberships set role='platform_admin' where id=md5('member-1-agent')::uuid$$,'23514',null,'platform is not a client role');
select throws_ok($$update organization_memberships set role='agent' where id=md5('member-1-client_admin')::uuid$$,'23514','Last active administrator','last admin cannot be demoted');
select throws_ok($$update professional_profiles set status='inactive' where id=md5('user-1-client_admin')::uuid$$,'23514','Last active administrator','last admin profile cannot be disabled');
select throws_ok($$update service_schedule_versions set timezone='UTC' where organization_id=md5('org-1')::uuid$$,'23514','Published schedule is immutable','schedule version immutable');
select throws_ok($$update sla_targets set duration_seconds=5 where organization_id=md5('org-1')::uuid$$,'23514','Published SLA is immutable','target immutable');
select throws_ok($$delete from sla_policy_versions where organization_id=md5('org-1')::uuid$$,'23514','Published SLA is immutable','SLA cannot be deleted');
select throws_ok($$update territories set parent_id=md5('territory-2')::uuid where id=md5('territory-1')::uuid$$,'23514',null,'invalid parent/cycle denied');
select throws_ok($$update territories set geometry=st_multi(st_geomfromtext('POLYGON((0 0,0.5 0,0.5 0.5,0 0.5,0 0))',4326)) where id=md5('territory-1')::uuid$$,'23514',null,'parent cannot exclude child');
select throws_ok($$insert into territories(code,name,kind,geometry) values('empty','empty','site',st_geomfromtext('MULTIPOLYGON EMPTY',4326))$$,'23514',null,'empty geometry rejected');
select throws_ok($$insert into territories(code,name,kind,geometry) values('wrong','wrong','site',st_geomfromtext('MULTIPOLYGON(((0 0,1 0,1 1,0 0)))',3857))$$,'22023',null,'wrong SRID rejected');

select set_config('request.jwt.claim.sub',md5('user-1-agent')::uuid::text,true);
set local role authenticated;
select is((select count(*) from services),1::bigint,'agent sees only own active service');
select is((select count(*) from organization_memberships),1::bigint,'agent sees only own membership');
select is((select count(*) from professional_profiles),1::bigint,'agent sees only own profile');
select is((select count(*) from contracts),0::bigint,'agent cannot read commercial contracts');
select is((select count(*) from audit_events),0::bigint,'agent cannot read audit');
select throws_ok($$select save_service(md5('org-1')::uuid,'evil','evil')$$,'42501',null,'agent cannot administer');
select throws_ok($$update services set name='evil'$$,'42501',null,'direct mutations denied');
select throws_ok($$insert into platform_admins(id,capabilities) values(auth.uid(),array['audit.read'])$$,'42501',null,'no self-promotion');
reset role;
select set_config('request.jwt.claim.sub',md5('user-1-supervisor')::uuid::text,true);
set local role authenticated;
select is((select count(*) from organization_memberships),2::bigint,'supervisor sees only members of supervised service');
select is((select count(*) from services),1::bigint,'supervisor sees supervised services');
select throws_ok($$select save_service(md5('org-1')::uuid,'evil','evil')$$,'42501',null,'supervisor not administrator');
reset role;
select set_config('request.jwt.claim.sub',md5('user-1-client_admin')::uuid::text,true);
set local role authenticated;
select is((select count(*) from services),2::bigint,'admin sees own organization services');
select is((select count(*) from organization_memberships),3::bigint,'admin sees own organization members');
select is((select count(*) from contracts),1::bigint,'admin can read own contract');
select throws_ok($$select save_contract(md5('org-1')::uuid,'evil','active',now(),null,'mvp')$$,'42501',null,'admin cannot expand contract');
select throws_ok($$select save_service(md5('org-2')::uuid,'evil','evil')$$,'42501',null,'cross-tenant admin mutation denied');
select lives_ok($$select save_service(md5('org-1')::uuid,'tested','Tested')$$,'authorized configuration mutation');
select ok(exists(select 1 from audit_events where actor_id=auth.uid() and entity_type='services' and action='INSERT'),'real actor audit');
select throws_ok($$delete from audit_events$$,'42501',null,'audit cannot be deleted directly');
select lives_ok($$select publish_schedule(md5('org-1')::uuid,null,'Europe/Paris','always_open','[]')$$,'publish next calendar version');
select is((select count(*) from service_schedule_versions),2::bigint,'old version retained');
select throws_ok($$select publish_schedule(md5('org-1')::uuid,null,'Bad/Zone','always_open','[]')$$,'23514',null,'invalid IANA timezone denied');
select throws_ok($$select publish_schedule(md5('org-1')::uuid,null,'Europe/Paris','weekly','[]')$$,'23514',null,'weekly requires seven days');
select is((select count(*) from coverage_candidates(0,0,(select id from categories where code='blocked_access' limit 1))),1::bigint,'boundary covered');
select is((select count(*) from coverage_candidates(-1,-1,(select id from categories where code='blocked_access' limit 1))),0::bigint,'outside uncovered');
reset role;
-- An audit failure must roll back the business write, including direct SQL.
create function pg_temp.fail_audit() returns trigger language plpgsql as $$begin raise exception 'Injected audit failure'; end$$;
create trigger injected_failure before insert on audit_events for each row execute function pg_temp.fail_audit();
select throws_ok($$insert into services(organization_id,code,name) values(md5('org-1')::uuid,'must-rollback','Must rollback')$$,'P0001','Injected audit failure','audit failure aborts mutation');
select is((select count(*) from services where code='must-rollback'),0::bigint,'failed audit leaves no business row');
drop trigger injected_failure on audit_events;
-- Existing JWT identity loses rights immediately after membership deactivation.
update organization_memberships set status='inactive' where id=md5('member-1-agent')::uuid;
select set_config('request.jwt.claim.sub',md5('user-1-agent')::uuid::text,true);
set local role authenticated;
select is((select count(*) from services),0::bigint,'inactive membership with unchanged identity has no rights');
reset role;
set local role anon;
select throws_ok($$select * from services$$,'42501',null,'anonymous business access denied');
reset role;
select * from finish();
rollback;
